---
- hosts: master_nodes
  become: yes
  vars_files:
  - ../edit.vars.yml
  roles:
    - { role: k8s/master}   

- hosts: worker_nodes
  become: yes
  vars_files:
  - ../edit.vars.yml
  roles:
    - { role: k8s/node}
