- name: restart containerd
  service: 
    name: containerd 
    state: restarted
    enabled: true
    daemon_reload: yes

- name: restart kubelet
  service: 
    name: kubelet 
    state: restarted 
    enabled: true
    daemon_reload: yes
